### ISSUE TITLE
Remove "root_formula" argument

### ISSUE THREAD

**Issue by ashb** [ministryofjustice/salt-shaker#19]
Specifying a root formula allows salt-shaker to operate without a formula checked out, but we don't actually ever need or want this - we always invoke it from a checkout, so just look for a metadata.yml file.

This might be as simple as removing these blocks https://github.com/ministryofjustice/salt-shaker/blob/f7ab3acca99aa24b58d6d14f747c1d7b1daeac2c/shaker/salt_shaker.py#L426-L440 and correcting anywhere that calls that (probably just the ShakerCommandLine module)

**Comment by niallcreech** [comment]
Removing root formula 

* Get root_formula from metadata.yml name key, make it mandatory
* Remove any fallbacks to getting root_formula name form e.g. env variables

Protect nested root dependency
* Make sure get_reqs_recursive passes this root formula up in root_formulas 

Should simplify everything quite well

**Comment by niallcreech** [comment]
Covering in #27
