### ISSUE TITLE
Refactor Code into Classes

### ISSUE THREAD

**Issue by niallcreech** [ministryofjustice/salt-shaker#27]
Move lots of code around into sane classes. Restructuring the flow should allow for the easy removal of a number of outstanding issues, specifically,

#26 Move functions to in-class methods
#25  Expand Code Comments
#19 Remove "root_formula" argument ready for review
#4 Deal with current formula being a dependency of another formula in progress

**Comment by bennythejudge** [comment]
Update:
1) executed tests to verify the behaviour of the algorithm to work out versions
2) added a test-requirements.txt
3) done more work on code improvement


To do:
1) branches must be accepted too in metadata.yml
2) add mock to test-requirements
3) improve logging during salt-shaker runs without verbose or debugging

**Comment by niallcreech** [comment]
https://github.com/ministryofjustice/salt-shaker/pull/30
