### ISSUE TITLE
Print messages to update user

### ISSUE THREAD

**Issue by bennythejudge** [ministryofjustice/salt-shaker#33]
In absence of anomalies, the command 

```
salt-shaker.py install
```

will not print any message at all.
Print something to inform of progress, without being spammy

**Comment by niallcreech** [comment]
This should be covered by the refactor_metadata branch

$ salt-shaker install
INFO:salt-shaker:Shaker::install_requirements: Updating and Installing requirements...all dependencies will be re-calculated from the metadata
INFO:salt-shaker:Shaker: Updating the formula requirements...
INFO:salt-shaker:Shaker::install_requirements: Updating requirements tag target shas
INFO:salt-shaker:Shaker::install_requirements: Installing requirements...
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'nginx-formula' from raw sha 'd5983558861db0496acb8100ee2ad6281dec28f5'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'supervisor-formula' from raw sha '88fa9cefb0ea7f31d746ddc12312bcae09d4494f'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'apparmor-formula' from raw sha '2664d307c4787d639cc0d5a488ed9ea0fd308bb6'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'firewall-formula' from raw sha '09760f5aebfdbc68a5c977c3c9034186560bbe7e'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'php-fpm-formula' from raw sha '4e26bb73944d0e7bd721e270382edc3a857b9647'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'python-formula' from raw sha '7c163fdb9f6696ed0799837435e3d1e6daa7b433'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'repos-formula' from raw sha '3d2e03826adc112b6bfed45b8d743dfb0fd1d274'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'bootstrap-formula' from raw sha 'f026b8f337fb3ef4f6e0ed4ccad70aac6b75855a'...OK
INFO:salt-shaker:Shaker: Writing requirements file...

**Comment by niallcreech** [comment]
$ salt-shaker install-pinned-versions
INFO:salt-shaker:Shaker::install_requirements: Installing pinned requirements...dependencies will be installed from the stored formula requirements
INFO:salt-shaker:Shaker: Loading the current formula requirements...
INFO:salt-shaker:Shaker::install_requirements: No remote check, not updating tag target shas
INFO:salt-shaker:Shaker::install_requirements: Installing requirements...
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'nginx-formula' from tag 'v3.2.3'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'supervisor-formula' from tag 'v1.2.0'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'apparmor-formula' from tag 'v1.0.1'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'firewall-formula' from tag 'v2.0.0'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'php-fpm-formula' from tag 'v1.0.9'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'python-formula' from tag 'v1.1.0'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'repos-formula' from tag 'v1.1.1'...OK
INFO:salt-shaker:ShakerRemote::install_dependencies: Updating 'bootstrap-formula' from tag 'v2.1.2'...OK
