### ISSUE TITLE
Deal with current formula being a dependency of another formula

### ISSUE THREAD

**Issue by milosgajdos83** [ministryofjustice/salt-shaker#4]
This happens if the working formula (which is your root formula) dependency depends on itself via some other formula.

In other words - we must find a way to avoid cyclic dependency of the working formula.

It's easier to explain it on an example:
You're working on `working_formula`. You run `salt-shaker` to resolve formula dependencies. Now, if one of the dependencies depend back on the `working_formula` ie. the formula you're working on, this will get pulled in again and vendored, and you are screwed because due to how `kitchen-salt` works, this will be overriding your `working_formula` changes on the test machine when the tests are run.

**Comment by ashb** [comment]
Some cycles are already handled. For instance if we have:

a -> b -> c -> d -> b

then this is handled fine and b isn't pulled in more than once, but if we have this case of 

a -> b -> c -> a

(where a is actually the formula-repo we are running `salt-shaker shake` from) then we would pull in *another copy* of a that would overlay the current checkout

**Comment by ashb** [comment]
https://trello.com/c/mWPfRsLI

**Comment by niallcreech** [comment]
Need to fill out the test cases

**Comment by niallcreech** [comment]
Finished more in depth tests

**Comment by niallcreech** [comment]
Covering in #27
